# Generated by Django 5.0.2 on 2025-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(max_length=100)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(blank=True, choices=[('bigha', 'Bigha'), ('cottah', 'Cottah'), ('acre', 'Acre'), ('decimal', 'Decimal')], max_length=20, null=True)),
                ('requirement_type', models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale'), ('joint_venture', 'Joint Venture')], max_length=20)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Land Requirement',
                'verbose_name_plural': 'Land Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
