# Generated by Django 5.0.2 on 2025-07-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequirement',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
