# Generated by Django 5.2.6 on 2025-11-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_leads', '0002_landrequirement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequirement',
            name='enquiry_from',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('owner', 'Owner'), ('individual', 'Individual')], max_length=20, null=True),
        ),
    ]
