# Generated by Django 5.0.2 on 2025-07-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAmenityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(help_text='e.g. Swimming Pool, Gym, Clubhouse', max_length=100)),
                ('image', models.ImageField(help_text='Upload amenity image', upload_to='project/amenities/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_images', to='Projects.project')),
            ],
            options={
                'verbose_name': 'Project Amenity Image',
                'verbose_name_plural': 'Project Amenity Images',
                'ordering': ['project', 'amenity_name', 'uploaded_at'],
            },
        ),
    ]
