# Generated by Django 5.0.2 on 2025-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_projectamenityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, help_text='Amenity description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='City description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, help_text='Project type description for SEO', null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200, null=True),
        ),
    ]
