# Generated by Django 5.0.2 on 2025-07-07 06:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_amenity_description_amenity_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='project/banner/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bhk',
            field=models.CharField(blank=True, help_text='e.g. 2, 3, 4 BHK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_up_area',
            field=models.CharField(blank=True, help_text='e.g. 1200 sq ft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Projects.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.CharField(blank=True, help_text='Developer name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_blocks',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_units',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='onwards_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_by',
            field=models.CharField(blank=True, help_text='Company or Brand', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Projects.projecttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('upcoming', 'Upcoming'), ('sold_out', 'Sold Out')], default='under_construction', max_length=20, null=True),
        ),
    ]
