# Generated by Django 5.2.4 on 2025-08-12 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_project_banner_image_alter_project_bhk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='feature_image',
            field=models.ImageField(blank=True, help_text='Amenity feature image', null=True, upload_to='amenities/images/'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='font_awesome_icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-swimming-pool)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nearestarea',
            name='icon',
            field=models.ImageField(blank=True, help_text='Location type icon', null=True, upload_to='locations/icons/'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rera_number',
            field=models.CharField(blank=True, help_text='RERA approval number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_office_address',
            field=models.TextField(blank=True, help_text='Sales office address', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.CharField(blank=True, help_text='e.g. 5.2 Acres', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tower_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of towers/blocks', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='nearestarea',
            name='area_type',
            field=models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('metro', 'Metro Station'), ('mall', 'Shopping Mall'), ('restaurant', 'Restaurant'), ('park', 'Park'), ('airport', 'Airport'), ('bus_stop', 'Bus Stop'), ('bank', 'Bank'), ('atm', 'ATM'), ('gym', 'Gym'), ('temple', 'Temple'), ('church', 'Church'), ('mosque', 'Mosque'), ('other', 'Other')], max_length=20),
        ),
    ]
