# Generated by Django 5.0.2 on 2025-09-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_amenity_feature_image_amenity_font_awesome_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_accesses', to='Projects.project')),
            ],
            options={
                'verbose_name': 'Floor Plan Access',
                'verbose_name_plural': 'Floor Plan Accesses',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['project', 'email'], name='Projects_fl_project_5198f3_idx'), models.Index(fields=['accessed_at'], name='Projects_fl_accesse_f9e6d8_idx')],
            },
        ),
    ]
