# Generated by Django 5.2.6 on 2025-10-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_floorplanaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='marketing_type',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent'), ('lease', 'Lease')], help_text='Marketing promotion type', max_length=10, null=True),
        ),
    ]
