# Generated by Django 5.2.6 on 2025-10-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_project_marketing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='marketing_type',
        ),
        migrations.AddField(
            model_name='project',
            name='is_lease',
            field=models.BooleanField(default=False, help_text='Available for Lease'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_rent',
            field=models.BooleanField(default=False, help_text='Available for Rent'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_sell',
            field=models.BooleanField(default=False, help_text='Available for Sell'),
        ),
    ]
