# Generated by Django 5.2.6 on 2025-10-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_remove_project_marketing_type_project_is_lease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Name of reviewer', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1-5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, help_text='Mark true to display on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Projects.project')),
            ],
            options={
                'verbose_name': 'Project Review',
                'verbose_name_plural': 'Project Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
