# Generated by Django 5.2.6 on 2025-10-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='reviewer_email',
            field=models.EmailField(blank=True, help_text='Email (for user reviews)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='reviewer_phone',
            field=models.CharField(blank=True, help_text='Phone (for user reviews)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Added'), ('user', 'User Submitted')], default='admin', help_text='Review source', max_length=10),
        ),
    ]
