# Generated by Django 5.2.6 on 2025-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_projectreview_reviewer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreview',
            name='reviewer_email',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='reviewer_phone',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='source',
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='approved',
            field=models.BooleanField(default=True, help_text='Mark true to display on frontend'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='comment',
            field=models.TextField(blank=True, help_text='Review comment', null=True),
        ),
    ]
