# Generated by Django 5.2.6 on 2025-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0016_finalize_area_type_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Display position (lower number = higher priority). Use 0 for default ordering by created date.'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['display_order', '-created_at'], name='Projects_pr_display_58d1fc_idx'),
        ),
    ]
