# Generated by Django 5.2.6 on 2025-11-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0017_alter_project_options_project_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interest', models.CharField(blank=True, choices=[('buying', 'Buying'), ('investment', 'Investment'), ('site_visit', 'Schedule Site Visit'), ('floor_plans', 'Floor Plans'), ('pricing', 'Pricing Details')], max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, help_text='Preferred appointment date', null=True)),
                ('appointment_time', models.CharField(blank=True, help_text='Preferred appointment time', max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Mark as contacted')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='Projects.project')),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'email'], name='Projects_pr_project_522964_idx'), models.Index(fields=['created_at'], name='Projects_pr_created_3e707c_idx'), models.Index(fields=['is_contacted'], name='Projects_pr_is_cont_e75bea_idx')],
            },
        ),
    ]
