# Generated by Django 5.2.6 on 2025-11-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0018_projectinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=250, null=True),
        ),
    ]
