# Generated by Django 5.2.6 on 2025-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0021_add_promotional_toggles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_editors_choice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_hot_deal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_lease',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_most_viewed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_nearby_property',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_premium_listing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_recently_viewed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_rent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_sell',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trending_tag',
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_commercial_projects',
            field=models.BooleanField(default=False, help_text='Show in Commercial Projects section', verbose_name='COMMERCIAL PROJECTS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_for_lease',
            field=models.BooleanField(default=False, help_text='Show in Properties for Lease section', verbose_name='PROPERTIES FOR LEASE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_for_rent',
            field=models.BooleanField(default=False, help_text='Show in Properties for Rent section', verbose_name='PROPERTIES FOR RENT'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_for_sale',
            field=models.BooleanField(default=False, help_text='Show in Properties for Sale section', verbose_name='PROPERTIES FOR SALE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_hot_deals',
            field=models.BooleanField(default=False, help_text='Show in Hot Deals section', verbose_name='HOT DEALS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_most_viewed',
            field=models.BooleanField(default=False, help_text='Show in Most Viewed section', verbose_name='MOST VIEWED'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_premium_projects',
            field=models.BooleanField(default=False, help_text='Show in Premium Projects section', verbose_name='PREMIUM PROJECTS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_recently_viewed',
            field=models.BooleanField(default=False, help_text='Show in Recently Viewed section', verbose_name='RECENTLY VIEWED'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_residential_projects',
            field=models.BooleanField(default=False, help_text='Show in Residential Projects section', verbose_name='RESIDENTIAL PROJECTS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promo_trending_projects',
            field=models.BooleanField(default=False, help_text='Show in Trending Projects section', verbose_name='TRENDING PROJECTS'),
        ),
    ]
