# Generated by Django 5.2.6 on 2025-11-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_remove_legacy_promotional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
