[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn Source.wsgi:application --bind 0.0.0.0:$PORT'
