[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x', 'npm']

[phases.install]
cmds = [
    'pip install -r requirements-deploy.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn Source.wsgi:application --bind 0.0.0.0:$PORT'
nixPkgs = ['python311']

[phases.install]
cmds = [
    'pip install -r requirements-railway.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn Source.wsgi:application --bind 0.0.0.0:$PORT'
