[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x', 'yarn', 'gcc', 'pkg-config', 'cairo', 'pango', 'libpng', 'jpeg', 'giflib', 'librsvg']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd theme/static_src && npm install && npm run build'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'python manage.py migrate'
]

[start]
cmd = 'gunicorn Source.wsgi:application --bind 0.0.0.0:$PORT'
