# Generated by Django 5.2.4 on 2025-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investment Opportunity', 'verbose_name_plural': 'Investment Opportunities'},
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='current_status',
            field=models.CharField(blank=True, help_text='Current status of the property', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='expected_roi',
            field=models.CharField(blank=True, help_text='Expected Return on Investment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='investment_duration',
            field=models.CharField(blank=True, help_text='Investment period/duration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='property_image_1',
            field=models.ImageField(blank=True, help_text='Primary property image', null=True, upload_to='investment/property_images/'),
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='property_image_2',
            field=models.ImageField(blank=True, help_text='Secondary property image', null=True, upload_to='investment/property_images/'),
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='property_image_3',
            field=models.ImageField(blank=True, help_text='Additional property image', null=True, upload_to='investment/property_images/'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='enquiry_from',
            field=models.CharField(choices=[('agent', 'Agent'), ('owner', 'Owner'), ('individual', 'Individual'), ('broker', 'Broker'), ('investor', 'Investor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('banquet', 'Banquet'), ('petrol_pump', 'Petrol Pump'), ('land', 'Land'), ('showroom', 'Showroom'), ('mall', 'Shopping Mall'), ('office_complex', 'Office Complex'), ('hospital', 'Hospital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale'), ('want_lease', 'Want Lease'), ('for_lease', 'For Lease'), ('partnership', 'Partnership'), ('joint_venture', 'Joint Venture')], max_length=20),
        ),
    ]
