# Generated by Django 5.2.4 on 2025-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_leads', '0002_alter_investmentrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investment Lead', 'verbose_name_plural': 'Investment Leads'},
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='enquiry_from',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='expected_roi',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='investment_duration',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='property_details',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='property_image_1',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='property_image_2',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='property_image_3',
        ),
        migrations.RemoveField(
            model_name='investmentrequirement',
            name='property_type',
        ),
        migrations.AddField(
            model_name='investmentrequirement',
            name='how_did_you_know',
            field=models.CharField(blank=True, choices=[('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('referral', 'Friend/Family Referral'), ('newspaper', 'Newspaper'), ('outdoor_ads', 'Outdoor Advertisements'), ('tv_ads', 'Television Ads'), ('radio', 'Radio'), ('website', 'Our Website'), ('email', 'Email Marketing'), ('other', 'Other')], max_length=20, null=True, verbose_name='How did you get to know about us?'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Agreed to Terms'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='budget',
            field=models.CharField(max_length=100, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='investmentrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=20, verbose_name='Requirement Type'),
        ),
    ]
