# Generated by Django 5.2.6 on 2025-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('service_type', models.CharField(choices=[('residential', 'Residential Interior'), ('commercial', 'Commercial Interior'), ('modular', 'Modular Solutions'), ('3d_visualization', '3D Visualization'), ('furniture', 'Furniture & Decor'), ('renovation', 'Renovation & Remodeling'), ('other', 'Other')], default='residential', max_length=50, verbose_name='Service Type')),
                ('project_details', models.TextField(help_text='Tell us about your project', verbose_name='Project Details')),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget Range')),
                ('timeline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Expected Timeline')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Location')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('consultation', 'Consultation Scheduled'), ('quoted', 'Quote Sent'), ('converted', 'Converted to Project'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Contacted On')),
            ],
            options={
                'verbose_name': 'Interior Inquiry',
                'verbose_name_plural': 'Interior Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
