# Generated by Django 5.2.6 on 2025-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('modular', 'Modular Solutions'), ('3d_visualization', '3D Visualization'), ('furniture', 'Furniture & Decor'), ('renovation', 'Renovation & Remodeling')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='interior/services/', verbose_name='Service Image')),
                ('badge_text', models.CharField(blank=True, choices=[('popular', 'Popular'), ('professional', 'Professional'), ('trending', 'Trending'), ('new', 'New')], max_length=50, verbose_name='Badge Label')),
                ('icon_class', models.CharField(default='fas fa-home', help_text='e.g., fas fa-home, fas fa-building', max_length=100, verbose_name='Font Awesome Icon Class')),
                ('features', models.TextField(help_text='Enter each feature on a new line', verbose_name='Features (one per line)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Service',
                'verbose_name_plural': 'Interior Services',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('work_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('modular', 'Modular'), ('renovation', 'Renovation')], max_length=50, verbose_name='Work Type')),
                ('image', models.ImageField(upload_to='interior/portfolio/', verbose_name='Project Image')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Location')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Project')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Work',
                'verbose_name_plural': 'Portfolio Works',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
