# Generated by Django 5.2.6 on 2025-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_interiorservice_portfoliowork'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+91 98765 43210', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(default='interior@velocityrealtor.com', max_length=254, verbose_name='Email Address')),
                ('office_address', models.TextField(default='123 Design Street, Kolkata, West Bengal 700001', verbose_name='Office Address')),
                ('whatsapp_number', models.CharField(blank=True, help_text='e.g., +919876543210', max_length=20, null=True, verbose_name='WhatsApp Number (with country code)')),
                ('page_title', models.CharField(default='Interior Design Services', max_length=200, verbose_name='Page Title')),
                ('page_description', models.TextField(default='Transform your space with our professional interior design services', verbose_name='Page Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Configuration',
                'verbose_name_plural': 'Interior Configuration',
            },
        ),
    ]
