# Generated by Django 5.2.4 on 2025-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(max_length=100)),
                ('budget_range', models.CharField(blank=True, choices=[('under_10l', 'Under 10 Lakhs'), ('10l_25l', '10 - 25 Lakhs'), ('25l_50l', '25 - 50 Lakhs'), ('50l_1cr', '50 Lakhs - 1 Crore'), ('1cr_2cr', '1 - 2 Crores'), ('2cr_5cr', '2 - 5 Crores'), ('5cr_plus', '5+ Crores')], max_length=20, null=True)),
                ('requirement_type', models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land'), ('office', 'Office Space'), ('retail', 'Retail Space'), ('warehouse', 'Warehouse')], max_length=20)),
                ('area_needed', models.CharField(blank=True, max_length=100, null=True)),
                ('specific_requirements', models.TextField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Requirement',
                'verbose_name_plural': 'Property Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
