# Generated by Django 5.2.6 on 2025-10-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='enquiry_from',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('owner', 'Owner'), ('individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='property_details',
            field=models.TextField(blank=True, help_text='Additional property details', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land'), ('office', 'Office Space'), ('retail', 'Retail Space'), ('warehouse', 'Warehouse'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('banquet', 'Banquet'), ('petrol_pump', 'Petrol Pump'), ('showroom', 'Showroom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease'), ('want_lease', 'Want Lease'), ('for_lease', 'For Lease')], max_length=20, null=True),
        ),
    ]
