# Generated by Django 5.2.6 on 2025-11-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirement_enquiry_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='property_details',
        ),
    ]
