# CKEditor config
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}
"""
Django settings for Source project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import shutil
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-8!zqd-sbw8z9u!^lp^@tx&g%l(_e6)#v(q(z*@foszhft5)*8u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'  # Enable debug temporarily to see errors

# Railway deployment and local development hosts
ALLOWED_HOSTS = ['*']  # Railway requires this for deployment

# CSRF settings for Railway deployment
CSRF_TRUSTED_ORIGINS = [
    'https://velocityrealtor.up.railway.app',
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://django-app.railway.internal'
]

# CSRF cookie settings for production
CSRF_COOKIE_SECURE = not DEBUG  # Only secure in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Session cookie settings for production
SESSION_COOKIE_SECURE = not DEBUG  # Only secure in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme - must be before django.contrib.admin
    'unfold.contrib.filters',  # Optional: Advanced filters
    'unfold.contrib.forms',  # Optional: Better form widgets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'theme',   # Custom theme app
    
    'Projects', # Custom app for core functionality
    'land_leads',  # Land requirements app
    'investment_leads',  # Investment requirements app
    'requirements',  # Property requirements app
    'interior',  # Interior design inquiries app
    'ckeditor',  # HTML editor support
    'blogs',     # New blogs app
    'career',    # Career app for job listings and applications
]


TAILWIND_APP_NAME = 'theme' # This is the name of the app that will be used to generate the tailwind files
INTERNAL_IPS = ['127.0.0.1']
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

#NPM_BIN_PATH='/user/local/bin/npm'

#Automatically resolve npm path (default to /usr/local/bin/npm if not found)
#NPM_BIN_PATH = shutil.which("npm") or "/usr/local/bin/npm"







MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for static files on Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Source.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'theme' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'theme.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'Source.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for simplicity in deployment
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'theme' / 'static',
    BASE_DIR / 'static',
]

# Static files storage for Railway
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files finder
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production settings
import os

# Environment-based configuration
if not DEBUG:
    # Production static files settings
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    
    # Security settings for production (disabled for Railway deployment)
    # SECURE_BROWSER_XSS_FILTER = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_REDIRECT_EXEMPT = []
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    
    # Railway deployment allows any host
    # ALLOWED_HOSTS is already set above for Railway compatibility
    
    # Logging configuration
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
            },
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'django.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': True,
            },
            'theme': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }

# ============================================================================
# UNFOLD ADMIN THEME CONFIGURATION
# ============================================================================
# Modern, clean admin interface with dark mode support
# Documentation: https://unfoldadmin.com/

UNFOLD = {
    "SITE_TITLE": "VeloCity Realtor",
    "SITE_HEADER": "VeloCity Realtor Admin",
    "SITE_URL": "/",
    "SITE_SYMBOL": "🏢",  # Emoji or Unicode symbol shown in dark mode
    
    "SHOW_HISTORY": True,  # Show history/change logs
    "SHOW_VIEW_ON_SITE": True,  # Show "View on site" link for models with get_absolute_url
    
    "COLORS": {
        "primary": {
            "50": "220 252 231",
            "100": "187 247 208", 
            "200": "134 239 172",
            "300": "74 222 128",
            "400": "34 197 94",
            "500": "22 163 74",  # Main primary color (green theme)
            "600": "21 128 61",
            "700": "20 83 45",
            "800": "22 101 52",
            "900": "20 83 45",
            "950": "5 46 22",
        },
    },
    
    "SIDEBAR": {
        "show_search": True,  # Show search in sidebar
        "show_all_applications": True,  # Auto-discover and show all apps
    },
}

