# Generated by Django 5.2.4 on 2025-08-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, default='#', help_text='Facebook page URL', null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='#', help_text='Instagram profile URL', null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, default='#', help_text='YouTube channel URL', null=True, verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, default='#', help_text='X (formerly Twitter) profile URL', null=True, verbose_name='X (Twitter) URL')),
                ('linkedin_url', models.URLField(blank=True, default='#', help_text='LinkedIn company page URL', null=True, verbose_name='LinkedIn URL')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +919876543210)', max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('site_title', models.CharField(default='VeloCity Realtor', help_text='Website title', max_length=100, verbose_name='Site Title')),
                ('site_description', models.TextField(blank=True, help_text='Website description for SEO', null=True, verbose_name='Site Description')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True, verbose_name='Contact Phone')),
                ('show_social_media', models.BooleanField(default=True, help_text='Display floating social media icons on the website', verbose_name='Show Social Media Icons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
