# Generated by Django 5.0.2 on 2025-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='promo_popup_image',
            field=models.ImageField(blank=True, help_text='Square image for promotional popup (recommended 1:1 ratio, e.g. 400x400px)', null=True, upload_to='site/promo_popup/', verbose_name='Promotional Popup Image'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='promo_popup_name',
            field=models.CharField(blank=True, help_text='Name or title for the promotional popup image', max_length=100, null=True, verbose_name='Promotional Popup Name'),
        ),
    ]
