# Generated by Django 5.2.4 on 2025-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='office_address',
            field=models.TextField(blank=True, help_text='Complete office address including city, state, country', null=True, verbose_name='Office Address'),
        ),
    ]
