# Generated by Django 5.2.4 on 2025-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_siteconfig_office_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('budget', models.CharField(max_length=100, verbose_name='Budget')),
                ('investment_type', models.CharField(max_length=255, verbose_name='Investment Type')),
                ('investment_details', models.TextField(blank=True, null=True, verbose_name='Investment Details')),
                ('how_know_about_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='How did you get to know about us?')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Agreed to Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investment Lead',
                'verbose_name_plural': 'Investment Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('budget', models.CharField(max_length=100, verbose_name='Budget')),
                ('requirement_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, verbose_name='Requirement Type')),
                ('how_know_about_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='How did you get to know about us?')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Agreed to Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Requirement',
                'verbose_name_plural': 'Property Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
