# Generated by Django 5.2.4 on 2025-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_investmentlead_propertyrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentlead',
            name='investment_details',
        ),
        migrations.RemoveField(
            model_name='investmentlead',
            name='investment_type',
        ),
        migrations.AddField(
            model_name='investmentlead',
            name='requirements_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20, verbose_name='Requirements Type'),
        ),
        migrations.AlterField(
            model_name='investmentlead',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget'),
        ),
    ]
