# Generated by Django 5.2.4 on 2025-08-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_remove_investmentlead_investment_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrequirement',
            name='how_know_about_us',
        ),
        migrations.AddField(
            model_name='propertyrequirement',
            name='enquiry_from',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('owner', 'Owner'), ('individual', 'Individual')], max_length=20, null=True, verbose_name='Enquiry From'),
        ),
        migrations.AddField(
            model_name='propertyrequirement',
            name='property_details',
            field=models.TextField(blank=True, null=True, verbose_name='Property Details'),
        ),
        migrations.AddField(
            model_name='propertyrequirement',
            name='property_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('banquet', 'Banquet'), ('petrol_pump', 'Petrol Pump'), ('land', 'Land'), ('showroom', 'Showroom')], max_length=20, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertyrequirement',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='propertyrequirement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferred Location'),
        ),
        migrations.AlterField(
            model_name='propertyrequirement',
            name='requirement_type',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sale', 'Sale'), ('want_lease', 'Want Lease'), ('for_lease', 'For Lease')], max_length=20, null=True, verbose_name='Requirement Type'),
        ),
    ]
