# Generated by Django 5.2.4 on 2025-08-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_remove_propertyrequirement_how_know_about_us_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentLead',
        ),
        migrations.DeleteModel(
            name='PropertyRequirement',
        ),
    ]
