# Generated by Django 5.0.2 on 2025-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_delete_investmentlead_delete_propertyrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the developer/partner company', max_length=100, verbose_name='Developer Name')),
                ('logo', models.ImageField(help_text='Logo of the developer company (recommended: transparent PNG, 200x100px)', upload_to='developers/', verbose_name='Developer Logo')),
                ('website_url', models.URLField(blank=True, help_text='Official website of the developer', null=True, verbose_name='Website URL')),
                ('description', models.TextField(blank=True, help_text='Brief description about the developer', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this developer on the website', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which developers should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Main logo for the website (recommended: transparent PNG, 200x60px)', null=True, upload_to='site/logo/', verbose_name='Site Logo'),
        ),
    ]
