# Generated by Django 5.2.6 on 2025-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_developer_siteconfig_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the interior project', max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(help_text='Description of the interior project', verbose_name='Project Description')),
                ('category', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office Space'), ('retail', 'Retail Store'), ('restaurant', 'Restaurant'), ('other', 'Other')], help_text='Category of the interior project', max_length=20, verbose_name='Project Category')),
                ('image', models.ImageField(help_text='Main image of the interior project (recommended: 800x600px)', upload_to='interior/portfolio/', verbose_name='Project Image')),
                ('before_image', models.ImageField(blank=True, help_text='Before renovation image (optional)', null=True, upload_to='interior/portfolio/before/', verbose_name='Before Image')),
                ('project_area', models.CharField(blank=True, help_text='Area of the project (e.g., 1200 sq ft)', max_length=50, null=True, verbose_name='Project Area')),
                ('project_cost', models.CharField(blank=True, help_text='Cost of the project (e.g., ₹5,00,000)', max_length=100, null=True, verbose_name='Project Cost')),
                ('completion_date', models.DateField(blank=True, help_text='Date when the project was completed', null=True, verbose_name='Completion Date')),
                ('client_name', models.CharField(blank=True, help_text='Name of the client (optional)', max_length=100, null=True, verbose_name='Client Name')),
                ('location', models.CharField(blank=True, help_text='Location of the project', max_length=200, null=True, verbose_name='Project Location')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this project prominently', verbose_name='Is Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this project on the website', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which projects should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Portfolio Item',
                'verbose_name_plural': 'Interior Portfolio Items',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteriorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the interior service', max_length=200, verbose_name='Service Title')),
                ('short_description', models.CharField(help_text='Brief description for service cards', max_length=300, verbose_name='Short Description')),
                ('description', models.TextField(help_text='Detailed description of the service', verbose_name='Detailed Description')),
                ('service_type', models.CharField(choices=[('residential', 'Residential Design'), ('commercial', 'Commercial Design'), ('modular', 'Modular Solutions'), ('3d_visualization', '3D Visualization'), ('furniture_decor', 'Furniture & Decor'), ('renovation', 'Renovation & Remodeling')], help_text='Type of interior service', max_length=20, verbose_name='Service Type')),
                ('image', models.ImageField(help_text='Image representing this service (recommended: 400x300px)', upload_to='interior/services/', verbose_name='Service Image')),
                ('icon_class', models.CharField(default='fas fa-home', help_text='FontAwesome icon class (e.g., fas fa-home)', max_length=50, verbose_name='Icon Class')),
                ('price_range', models.CharField(blank=True, help_text='Price range for this service (e.g., ₹50,000 - ₹2,00,000)', max_length=100, null=True, verbose_name='Price Range')),
                ('features', models.TextField(blank=True, help_text='Key features of this service (one per line)', null=True, verbose_name='Service Features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this service on the website', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which services should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Service',
                'verbose_name_plural': 'Interior Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InteriorTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client', max_length=100, verbose_name='Client Name')),
                ('client_designation', models.CharField(blank=True, help_text='Designation or title of the client', max_length=100, null=True, verbose_name='Client Designation')),
                ('client_photo', models.ImageField(blank=True, help_text='Photo of the client (recommended: square, 200x200px)', null=True, upload_to='interior/testimonials/', verbose_name='Client Photo')),
                ('testimonial', models.TextField(help_text='Client testimonial about interior design services', verbose_name='Testimonial')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=5, help_text='Rating out of 5 stars', verbose_name='Rating')),
                ('project_type', models.CharField(blank=True, help_text='Type of project (e.g., Home Interior, Office Design)', max_length=100, null=True, verbose_name='Project Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this testimonial on the website', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which testimonials should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Testimonial',
                'verbose_name_plural': 'Interior Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
