# Generated by Django 5.2.6 on 2025-10-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_interiorportfolio_interiorservice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteriorPortfolio',
        ),
        migrations.DeleteModel(
            name='InteriorService',
        ),
        migrations.DeleteModel(
            name='InteriorTestimonial',
        ),
    ]
