# Generated by Django 5.2.6 on 2025-11-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_delete_interiorportfolio_delete_interiorservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='company_brochure',
            field=models.FileField(blank=True, help_text='Upload company brochure PDF file for download on homepage', null=True, upload_to='site/brochures/', verbose_name='Company Brochure (PDF)'),
        ),
    ]
