# Generated by Django 5.2.6 on 2025-11-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_siteconfig_company_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sales_phone',
            field=models.CharField(blank=True, help_text="Sales or support phone number for 'Call Us Now' button", max_length=20, null=True, verbose_name='Sales/Support Phone'),
        ),
    ]
