# Generated by Django 5.2.6 on 2025-11-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_siteconfig_sales_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the client (Bengali names supported)', max_length=100, verbose_name='Client Name')),
                ('location', models.CharField(help_text='City or area (e.g., Kolkata, Saltlake, New Town)', max_length=100, verbose_name='Location')),
                ('designation', models.CharField(blank=True, help_text="Client's profession or designation (optional)", max_length=100, null=True, verbose_name='Designation/Profession')),
                ('company', models.CharField(blank=True, help_text='Company name (optional)', max_length=100, null=True, verbose_name='Company Name')),
                ('rating', models.IntegerField(choices=[(5, '5 Stars - Excellent'), (4, '4 Stars - Very Good'), (3, '3 Stars - Good'), (2, '2 Stars - Fair'), (1, '1 Star - Poor')], default=5, help_text='Client rating (1-5 stars)', verbose_name='Rating')),
                ('review_text', models.TextField(help_text="Client's testimonial/review (Bengali and English supported)", verbose_name='Review Text')),
                ('client_image', models.ImageField(blank=True, help_text='Client photo (optional, recommended: 200x200px)', null=True, upload_to='testimonials/', verbose_name='Client Photo')),
                ('project_type', models.CharField(blank=True, help_text='Type of project (e.g., Residential, Commercial, Office)', max_length=100, null=True, verbose_name='Project Type')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the website', verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured testimonials appear first', verbose_name='Is Featured')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
    ]
