# Generated by Django 5.2.6 on 2025-11-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (recommended: square PNG, 32x32px or 512x512px for best quality)', null=True, upload_to='site/favicon/', verbose_name='Favicon'),
        ),
    ]
