# Generated by Django 5.2.6 on 2025-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_siteconfig_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_image_desktop',
            field=models.ImageField(blank=True, help_text='Desktop hero section background image (recommended: 1920x1080px, landscape)', null=True, upload_to='site/hero/', verbose_name='Hero Background (Desktop)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_image_mobile',
            field=models.ImageField(blank=True, help_text='Mobile hero section background image (recommended: 750x1334px, portrait or square)', null=True, upload_to='site/hero/', verbose_name='Hero Background (Mobile)'),
        ),
    ]
